version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.release
    environment:
      PORT: 8080
      DATABASE_URL: ecto://postgres:postgres@postgresql/live_view_demo_dev
      SITE_HOST: localhost
      SITE_SCHEME: http
      SITE_PORT: 8080
      SECRET_KEY_BASE: fXAMv+9hAbEjiltKEKx9UN/kaHph5pnhbN/YN/k7TbKA4ET/Bgo4j1aOvMiQXwKe
    ports:
      - '8080:8080'
  postgresql:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
